### ISSUE TITLE
Logigen install

### ISSUE THREAD

**Issue by gabrielhdt** [Deducteam/Logipedia#13]
Does logigen use python2 or python3?

When using python3, I encounter the error
```
Traceback (most recent call last):
  File "/home/koizumi/.local/bin/logigen", line 11, in <module>
    load_entry_point('logigen==0.0.1', 'console_scripts', 'logigen')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/koizumi/.local/lib/python3.5/site-packages/logigen/__init__.py", line 5, in <module>
    from .logigen import create_db, Logigen
  File "/home/koizumi/.local/lib/python3.5/site-packages/logigen/logigen.py", line 39
    logging.info(f"loading file {p} into database")
                                                 ^
SyntaxError: invalid syntax
```

and when I try `pip install .` with python2 pip, I get
```
  Could not find a version that satisfies the requirement sqlite-utils==1.11 (from logigen==0.0.1) (from versions: )
No matching distribution found for sqlite-utils==1.11 (from logigen==0.0.1)
```

**Comment by rprimet** [comment]
I think using python >= 3.7 should do the trick (although f-strings are part of 3.6).

**Comment by rprimet** [comment]
To clarify this I added the requirement to the `setup.cfg` file so that `pip` will enforce it automatically.

**Comment by gabrielhdt** [comment]
Indeed it works better.  However, if I run `logigen -i logipedia/export/json -o web`, I get
```
Traceback (most recent call last):
  File "/home/koizumi/.local/bin/logigen", line 10, in <module>
    sys.exit(create_static_website())
  File "/home/koizumi/.local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/koizumi/.local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/koizumi/.local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/koizumi/.local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/koizumi/.local/lib/python3.7/site-packages/logigen/__init__.py", line 41, in create_static_website

    Logigen.create_static_website(input_path, output_path)
  File "/home/koizumi/.local/lib/python3.7/site-packages/logigen/logigen.py", line 139, in create_static_website
    Logigen.create_static_website_from_db(dbfile.name, output_path)
  File "/home/koizumi/.local/lib/python3.7/site-packages/logigen/logigen.py", line 154, in create_static_website_from_db
    cls(db_path, output_path)._create_static_website()
  File "/home/koizumi/.local/lib/python3.7/site-packages/logigen/logigen.py", line 115, in _create_static_website
    self._ingest_db_objects()
  File "/home/koizumi/.local/lib/python3.7/site-packages/logigen/logigen.py", line 112, in _ingest_db_objects
    self._ingest_object(proof_object)
  File "/home/koizumi/.local/lib/python3.7/site-packages/logigen/logigen.py", line 107, in _ingest_object
    page = self._create_object_page(obj)
  File "/home/koizumi/.local/lib/python3.7/site-packages/logigen/logigen.py", line 84, in _create_object_page
    template = self.env.get_template("object.html")
  File "/home/koizumi/.local/lib/python3.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/koizumi/.local/lib/python3.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/koizumi/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/koizumi/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 235, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: object.html
```

**Comment by rprimet** [comment]
OK, this should be fixed now (missing package data)
